name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -j $(sysctl -n hw.logicalcpu) lib/ios/arm64/libcolmap.dylib
    - name: store
      uses: actions/upload-artifact@v3
      with:
        name: lib-ios
        path: lib

  build-iossimulator:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -j $(sysctl -n hw.logicalcpu) lib/iossimulator/x86_64/libcolmap.dylib
    - name: store
      uses: actions/upload-artifact@v3
      with:
        name: lib-iossim
        path: lib

  build-maccat:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -j $(sysctl -n hw.logicalcpu) lib/maccat/x86_64/libcolmap.dylib
    - name: store
      uses: actions/upload-artifact@v3
      with:
        name: lib-maccat
        path: lib

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -j $(sysctl -n hw.logicalcpu) lib/mac/x86_64/libcolmap.dylib
    - name: store
      uses: actions/upload-artifact@v3
      with:
        name: lib-mac
        path: lib

  build-nuget:
    runs-on: macos-latest
    needs: [build-ios, build-iossimulator, build-maccat, build-mac]
    steps:
    - uses: actions/checkout@v3
    - name: Download ios
      uses: actions/download-artifact@v3
      with:
        name: lib-ios
    - name: Download iossimulator
      uses: actions/download-artifact@v3
      with:
        name: lib-iossimulator
    - name: Download maccat
      uses: actions/download-artifact@v3
      with:
        name: lib-maccat
    - name: Download mac
      uses: actions/download-artifact@v3
      with:
        name: lib-mac
    - name: List lib
      run: ls -lR lib
    - name: Update Versions
      env:
        VERSION_PREFIX: 0.1
        VERSION_SUFFIX: ${{github.run_number}}
      run: |
        VERSION=$VERSION_PREFIX.$VERSION_SUFFIX
        sed -i.bak "s:<Version>1.0.0</Version>:<Version>$VERSION</Version>:g" ColmapSharp/ColmapSharp.csproj
        sed -i.bak "s:<version>1.0.0</version>:<version>$VERSION</version>:g" Praeclarum.ColmapSharp.nuspec
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.101
    - name: Install workloads
      run: dotnet workload install ios maccatalyst macos
    - name: Make managed
      run: make managed
    - name: Make nuget
      run: make nuget
    - name: Store nugets
      uses: actions/upload-artifact@v2
      with:
        name: ColmapSharpNugets
        path: "NugetPackages/*.nupkg"
